### ISSUE TITLE
Suggestion : Visible on HUD option

### ISSUE THREAD

**Issue by Psychogenic88** [BleachDrinker420/BleachHack#255] opened 2021-06-19 16:13 UTC
This is really only necessary for us that like to have a clean HUD/UI. 

Toggling visible on mods would allow for customization of which mods you prefer to show up onscreen.

Ex: If you have Freecam enabled and Visible turned off, the module will not show up in the array list/active mods list when toggled.

**Comment by BleachDrinker420** [comment] 2021-06-23 19:40
Duplicate of #223

**Closed by BleachDrinker420** 2021-06-23 19:40 UTC
